app:
  name: "coincooper_exchange"
  domain: "coincooper.com"
  subdomain: "ex"
ssl:
  enabled: true
  email: "noreply@coincooper.com"
images:
  peatio: rubykube/peatio:2.3.1
  barong: rubykube/barong:2.3.3 
  frontend: rubykube/mikroapp:0.1.5
  tower: rubykube/tower:0.1.17
  postmaster: quay.io/openware/postmaster:2.2.2
  arke: rubykube/arke:0.1.9
vendor:
  frontend: https://github.com/rubykube/mikroapp.git
storage:
  provider: "Google"
  bucketName: "microkube-barong-docs-bucket"
  accessKey: "**********"
  secretKey: "**********"
terraform:
  credentials: "~/safe/microkube.json"
  project: "example-microkube"
  region: "europe-west4"
  zone: "europe-west4-a"
  instance_name: "microkube-cloud"
  machine_type: "n1-standard-4"
  image: "debian-cloud/debian-9"
twilio:
  phone_number: "+15005550000"
  account_sid: "changeme"
  auth_token: "changeme"
sendgrid_api_key: changeme
arke:
  strategy:
    type: 'copy'
    pair: 'ETHUSD'
    target:
      driver: rubykube
      host: 'http://ex.coincooper.com'
      name: bala
      key: changeme
      secret: changeme
    sources:
      - driver: bitfinex
        name: Joe
        key: changeme
        secret: changeme
